import type { AppProps } from 'next/app'
import '../global/global.scss'
import Head from 'next/head'
import { MainLayout } from '../layouts/MainLayout/MainLayout'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Фермер.ру</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Component {...pageProps} />
      </MainLayout>
    </>
  )
}
